### ISSUE TITLE
re-doing W22084 with the bo option

### ISSUE THREAD

**Issue by eroux** [OpenPecha/ocr-queue#7]
BDRC will pay for re-doing https://github.com/OpenPecha/P007112/ with the [bo option](https://github.com/OpenPecha-dev/openpecha-toolkit/issues/111), the deadline would be November 15th. Is that possible?

**Comment by ngawangtrinley** [comment]
@ta4tsering could you do it?

**Comment by ta4tsering** [comment]
okay I will do it

**Comment by ta4tsering** [comment]
this https://github.com/OpenPecha-dev/openpecha-toolkit/issues/111 issue is not fixed yet

**Comment by 10zinten** [comment]
[here](https://github.com/OpenPecha/e7a2a7b36dc54d56af46981d0d728beb) re-done pecha with `bo` lang

**Comment by ngawangtrinley** [comment]
A. [image](https://iiif.bdrc.io/bdr:I0890::08900006.tif/full/max/0/default.png) - English instead of Hindi, I guess it's for འདུལ་བ་ on the side?

![](https://user-images.githubusercontent.com/17675331/141419403-8939cea6-fb24-4480-a517-e60e8227dcb9.png)

![](https://user-images.githubusercontent.com/17675331/141419441-18b721e9-128a-4cac-8e7c-0b5c84cbe7f6.png)

  
B. [image](https://iiif.bdrc.io/bdr:I0890::08900006.tif/full/max/0/default.png) - interesting extra text in new one on the right. 

![](https://user-images.githubusercontent.com/17675331/141419335-f96f3d5f-01ac-4279-a9a5-8800901e9e2a.png)

![](https://user-images.githubusercontent.com/17675331/141419281-725c91e0-cfa7-4659-865d-c864a7e5fba2.png)

C. [image](https://iiif.bdrc.io/bdr:I0890::08900013.tif/full/max/0/default.png) - improvements on the right in other places though. 

![](https://user-images.githubusercontent.com/17675331/141421223-78a3a0a3-66f9-4191-8cd1-88d4c73ca9aa.png)

![](https://user-images.githubusercontent.com/17675331/141421497-2363ccf3-82d8-4304-bffc-e1701b7e2547.png)

**Comment by eroux** [comment]
thanks a lot!!
